name: 'VSCDC smoke test'
inputs:
  definition:
    description: 'Definition to test'
    required: true
    default: 'debian'
  image:
    description: 'Image to run smoke test in'
    required: true
    default: 'none'

runs:
  using: composite
  steps:
    - name: Build image
      id: build_image
      shell: bash
      run: |
        set -e

        # Run test build
        yarn install
        GIT_BRANCH=$(echo "${{ github.ref }}" | grep -oP 'refs/(heads|tags)/\K(.+)')
        if [ "$GIT_BRANCH" == "" ]; then 
            GIT_BRANCH=main
        fi
        build/vscdc push  ${{ inputs.definition }} \
                          --no-push \
                          --release $GIT_BRANCH \
                          --github-repo "microsoft/vscode-dev-containers" \
                          --registry "mcr.microsoft.com" \
                          --registry-path "vscode/devcontainers" \
                          --stub-registry "mcr.microsoft.com" \
                          --stub-registry-path  "vscode/devcontainers"

    - name: Test image
      id: test_image
      shell: bash
      run: |
        if [ "${{ inputs.image }}" != "none" ]; then
          docker run --rm --init --privileged -v "$(pwd)/containers/${{ inputs.definition }}:/workspace" "${{ inputs.image }}" /bin/sh -c  '\
            cd /workspace \
            && echo "Environment:\n$(env)" \
            && if [ -f "test-project/test.sh" ]; then \
              cd test-project \
              && if [ "$(id -u)" = "0" ]; then \
                chmod +x test.sh; \
              else \
                sudo chmod +x test.sh; \
              fi \
              && ./test.sh; \
            else \
              ls -a; 
            fi'
        fi
