name: Smoke test "javascript-node" build

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]
    paths:
      - 'containers/javascript-node/**'
jobs:
  smoke-test:
    name: Smoke test
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2
    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: javascript-node
        image: mcr.microsoft.com/vscode/devcontainers/javascript-node:dev-debian
        user: vscode
