name: Test using image for action environment

on: 
  workflow_dispatch:
  push:
    # branches: [actions-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        cat $HOME/.docker/config.json

 

