name: Test Buildx

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - name: Test buildx
      run: |
        docker buildx create --use --name vscode-dev-containers
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx ls
        cd .devcontainer
        docker buildx build --build-arg INSTALL_GRADLE=true --build-arg INSTALL_MAVEN=true --build-arg INSTALL_NODE=true --platforms linux/arm64,linux/amd64 .

