name: Test

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/java:8
      options: -u vscode
    steps:
    - name: Test
      run: |
        id
        bash -i << 'BASHEOF'
        
        sdk version

        BASHEOF
 

