name: Misc test

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: node --version && npm --version && yarn --version