name: Test gpg

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor > /usr/share/keyrings/yarn-archive-keyring.gpg
        cat /usr/share/keyrings/yarn-archive-keyring.gpg

      

 

