name: Test custom action

on: 
  workflow_dispatch:
  push:
    branches: [actions-test]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v1
    - name: test action
      id: test_action
      uses: ./.github/actions/test-action
      with:
        option: true

